apiVersion: apps/v1
kind: Deployment
metadata:
 name: k8s-gb-go-backend2
spec:
 replicas: 2
 strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1
     maxSurge: 1
 selector:
   matchLabels:
     app: k8s-gb-go-backend2
 template:
   metadata:
     labels:
       app: k8s-gb-go-backend2
   spec:
     containers:
       - name: k8s-gb-go-backend2
         image: docker.io/alekseevdenis/gb-go-backend2:latest
         imagePullPolicy: Always
         ports:
           - containerPort: 8080
         livenessProbe:
           httpGet:
             path: /__heartbeat__
             port: 8080
             scheme: HTTP
           initialDelaySeconds: 5
           periodSeconds: 15
           timeoutSeconds: 5
         readinessProbe:
           httpGet:
             path: /__heartbeat__
             port: 8080
             scheme: HTTP
           initialDelaySeconds: 5
           timeoutSeconds: 1

